version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - db_alura:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alura



volumes:
  db_alura: